### PR TITLE
Add more functional tests

### PR DESCRIPTION
**Pull request by forus**

### CODE REVIEW

**Comment by forus** [comment]
@mkarmona Hi Miguel, please have a look.

**Comment by forus** [comment]
@mkarmona Please note that I removed email from Travis file to prevent you guys getting to much emails from the forks. The default Travis notification strategy seems to be reasonable https://docs.travis-ci.com/user/notifications/#how-is-the-build-email-receiver-determined

**Comment by mkarmona** [comment]
@forus you might want to have a look at [this file](https://github.com/opentargets/genetics-api/blob/19.05.25/app/models/FRM.scala) in order to get a better idea about which fields belong to which entity. It is also a good guide for you.

**Comment by forus** [comment]
@mkarmona thanks for the useful hint.

**Comment by forus** [comment]
@mkarmona I've just updated the classes to align with the api expectations.

**Comment by mkarmona** [comment]
@forus I updated the code as you introduced a subtle bug so I revert a [line here ](https://github.com/opentargets/genetics-pipe/blob/19.05.15/src/main/scala/ot/geckopipe/Main.scala#L222) so if you want to customise the default config just place an `application.conf` in the root of the project (where `build.sbt` lives) and then you can run it as this `"run build-all -f application.conf"` you can also use include inside this file to overwrite the default one. Please also note that the `spark-uri` needs `local[numerofcoresyouwanttouse]` otherwise it will be using just a single core!!

Something similar to this (this is outdated by serves as an example)
```hcon
// config to add
spark-uri = "local[*]"
log-level = "INFO" // DEBUG
sample-factor = 0.5 // sample > 0 then is enabled
output = "file:///home/mkarmona/tmp/ot/genetics-data/out/190401"
input = "file:///home/mkarmona/tmp/ot/genetics-data/in"

variant-index {
  raw = ${input}"/variant-annotation/190129/variant-annotation.parquet/"
  path = ${output}"/variant-index"
  tss-distance = 5000000
}

nearest {
  tss-distance = 5000
  path = ${output}"/distance/nearest/"
}

ensembl {
  lut = ${input}"/lut/homo_sapiens_core_96_38_genes.json"
}

vep {
  homo-sapiens-cons = ${input}"/vep/homo_sapiens_incl_consequences.tsv"
  homo-sapiens-cons-scores = ${input}"/lut/vep_consequences.tsv"
}

interval {
  path = ${input}"/v2g/190207/interval/*/*/data.parquet/"
}

qtl {
  path = ${input}"/v2g/190207/qtl/*/*/data.parquet/"
}

variant-gene {
  path = "out/v2g/*"
}

variant-disease {
  path = ${output}"/v2d/"
  studies = ${input}"/v2d/190521/studies.parquet"
  toploci = ${input}"/v2d/190521/toploci.parquet"
  finemapping = ${input}"/v2d/190521/finemapping.parquet"
  ld = ${input}"/v2d/190521/ld.parquet"
  overlapping = ${input}"/v2d/190521/locus_overlap.parquet"
  coloc = ${input}"/v2d/190521/coloc"
}

```

**Comment by forus** [comment]
@mkarmona Hi! Specifying `spark-uri` from a config file looks like a better alternative to me. Thanks for the suggestion. What was the subtle bug about?

**Comment by mkarmona** [comment]
@forus yes it was indeed. it is sorted it out right now by this URI change.

**Comment by forus** [comment]
@mkarmona I see `wip: test is no working properly` comment in the commit message here https://github.com/opentargets/genetics-pipe/commit/b01e4b756ce7b98067de2464ecdd7eb4d23f31b2

Do you have some changes to commit? I am working on rebasing the PR on the current master now and can take care to fix the commented test.

**Comment by mkarmona** [comment]
@forus I don't think I will commit any time soon to this repo. That would be great indeed. thanks!

**Pull request closed without merging**
