### PR TITLE
Add functional tests for the pipeline

### PR DESCRIPTION
**Pull request by forus**

### CODE REVIEW

**Comment by forus** [comment]
@mkarmona Hi Miguel, I've added a functional test to the pipeline. I am going to add more like that. I would like to ask for your feedback before that. What do you think about changes so far? Is there something I should take into account?

**Comment by mkarmona** [comment]
@forus sounds great! thanks for this addition. let me check that

**Review by mkarmona — APPROVED** [review]

**Comment by forus** [comment]
@mkarmona Do you mean `mk-generateranks` branch?

**Comment by mkarmona** [comment]
@forus no sorry. forget about it

**Pull request merged**
